name: Build and Deploy App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: time-tracker-frontend
      PROJECT_ID: <project-id>

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Log in to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GHCR_KEY }} ghcr.io

      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: |-
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker <server-env> --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag ${{ env.IMAGE_NAME }}:latest <server-env>/${{ env.PROJECT_ID }}/time-tracker-frontend/${{ env.IMAGE_NAME }}:latest
          docker push <server-env>/${{ env.PROJECT_ID }}/time-tracker-frontend/${{ env.IMAGE_NAME }}:latest

      - name: Deploy Docker Image with Google Cloud Run
        run: |-
          gcloud run deploy time-tracker-frontend --image gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest --platform managed --region asia-east1 --allow-unauthenticated --service-account ${{ secrets.GCP_SA_USER }}
